#:schema node_modules/wrangler/config-schema.json
name = "web-converter-3d"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
watch_dir = "src" # Adjust if your source code is in a specific folder, otherwise it defaults to monitoring everything.

[build.upload]
format = "directory"
